# Generated by Django 5.0.2 on 2024-04-29 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_owner'),
        ('orders', '0002_alter_order_сar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='сar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Арендованный автомобиль'),
        ),
    ]
