# Generated by Django 5.0.2 on 2024-05-01 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_status'),
        ('orders', '0006_order_is_lessor_start_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('renter', 'car')},
        ),
    ]
