# Generated by Django 5.0.2 on 2024-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UC', 'На рассмотрении'), ('AD', 'Одобрен'), ('IP', 'Выполняется'), ('CD', 'Отменен'), ('RD', 'Отклонен'), ('FD', 'Завершен')], default='UC', max_length=2, verbose_name='Статус'),
        ),
    ]
