repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/hakancelikdev/unimport
    rev: 1.2.1
    hooks:
    -   id: unimport
-   repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.4.0
    hooks:
    -   id: check-unapplied-migrations
    -   id: check-absent-migrations
-   repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: python car_rent/manage.py makemigrations --dry-run
        language: system
        types: [python]
        pass_filenames: false
