# Generated by Django 5.0.2 on 2024-04-21 09:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_brand_brand_title_gin_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(
                default=1, max_length=25, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('SE', 'Седан'), ('LF', 'Лифтбек'), ('CP', 'Купе'), ('H3', 'Хэтчбек 3 дв.'), ('H5', 'Хэтчбек 5 дв.'), ('SW', 'Универсал'), ('S3', 'Внедорожник 3 дв.'), (
                'S5', 'Внедорожник 5 дв.'), ('MV', 'Минивен'), ('PC', 'Пикап'), ('LM', 'Лимузин'), ('VN', 'Фургон'), ('CB', 'Кабриолет')], default=1, max_length=2, verbose_name='Тип кузова'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='drive',
            field=models.CharField(choices=[('RWD', 'Задний привод'), ('FWD', 'Передний привод'), (
                'AWD', 'Полный привод')], default=1, max_length=3, verbose_name='Привод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[
                                      django.core.validators.MinValueValidator(0.1)], verbose_name='Объем двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='gearbox',
            field=models.CharField(choices=[('MA', 'Механическая'), ('AU', 'Автоматическая'), (
                'AR', 'Робот'), ('AC', 'Вариатор')], default=1, max_length=2, verbose_name='Коробка передач'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='cars.carmodel', verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='langitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='car',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[
                                      django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.01)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='cars.brand', verbose_name='Марка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[
                                      django.core.validators.MinValueValidator(0.1)], verbose_name='Расход топлива'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='hp',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)], verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type_of_fuel',
            field=models.CharField(choices=[('92', 'АИ-92'), ('95', 'АИ-95'), ('10', 'АИ-100'), ('GS', 'Газ'), ('DT',
                                   'Дизельное топливо'), ('EL', 'Электричество')], default=1, max_length=2, verbose_name='Тип топлива'),
            preserve_default=False,
        ),
    ]
