# Generated by Django 5.0.2 on 2024-04-25 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_color_carmodel_body_type_carmodel_drive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car',
            new_name='car_model',
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[(100, 'Не проверено'), (200, 'Проверено'), (
                300, 'Архивировано'), (400, 'Заблокировано')], default=100, max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[
                                      django.core.validators.MinValueValidator(0.1)], verbose_name='Объем двигателя'),
        ),
    ]
