# Generated by Django 5.0.2 on 2024-05-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[(100, 'Не проверено'), (200, 'Проверено'), (300, 'Архивировано'), (400, 'Заблокировано')], default=100, verbose_name='Статус'),
        ),
    ]
