# Generated by Django 5.0.2 on 2024-04-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('NV', 'Не проверено'), ('VD', 'Проверено'), ('AD', 'Архивировано'), ('BD', 'Заблокировано')], default='NV', verbose_name='Статус'),
        ),
    ]
