# Generated by Django 5.0.2 on 2024-05-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_brandphoto_options_alter_carphoto_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarOptions',
            new_name='CarOption',
        ),
    ]
