# Generated by Django 5.0.2 on 2024-05-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_rename_caroptions_caroption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='langitude',
            new_name='longitude',
        ),
    ]
