# Generated by Django 5.0.2 on 2024-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_rename_langitude_car_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='photo',
            field=models.FileField(upload_to='cars', verbose_name='Фото'),
        ),
    ]
