# Generated by Django 5.0.2 on 2024-10-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PS', 'Физ. Лицо'), ('CM', 'Компания'), ('AD', 'Админ')], default='PS', max_length=2, verbose_name='Роль'),
        ),
    ]
